# Generated by Django 3.2 on 2022-01-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productreview_reccomended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='reccomended',
            new_name='recommended',
        ),
    ]
