# Generated by Django 3.2 on 2022-02-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_reccomended_productreview_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='stars',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=3),
        ),
    ]
